### ISSUE TITLE
Proposal — Testing AWS Serverless integrations with MongoDB using LocalStack

### ISSUE THREAD

**Issue by HarshCasper** [MUG-Chennai/Event-CFP#2]
* **Title**: Testing AWS Serverless integrations with MongoDB using LocalStack
* **Speaker**: @HarshCasper
* **LinkedIn**: https://www.linkedin.com/in/harshcasper
* **Resources**: https://github.com/localstack/localstack
* **Language**: English
* **Type**: Presentation 30-45 mins
* **Level**: Introduction
* **Tags**: serverless, testing, live-coding, workshop

**Description**

LocalStack is a fully functional local AWS cloud stack that enables cloud applications & infrastructure to be developed entirely on your local machine. LocalStack enables developers to create & deploy serverless Lambda functions on their local machine and emulate various APIs served via an ephemeral Docker container. With LocalStack, you can plug in your MongoDB database with AWS-native serverless integrations, while developing & testing your applications, completely locally.

In this session, we will demonstrate how you can use LocalStack to develop and test serverless integrations with MongoDB with interactive live coding to showcase common scenarios and use cases. We will also demonstrate some advanced new features that can radically improve productivity and team collaboration patterns while building these serverless integrations for your AWS cloud applications, powered by MongoDB.

**Speaker Bio**

Hi — I am Harsh, an engineer working at LocalStack. Previously, I was a Google Summer of Code student developer at MetaCall, and a Google Season of Docs technical writer at moja global. I have worked at HackerRank, Quansight, and Red Hat, to name a few, and I am passionate about Web Engineering, Python, DevOps, and Cloud in general. I have spoken at EuroPython '21, PyCon India '21, and GitKon '22.

**Comment by rishiagrawal2609** [comment]
Completed on Aug 5
